resources:
  webhooks:
    - webhook: testhook1          ### Webhook alias
      connection: FromGitHub    ### Incoming webhook service connection
      filters:
        - path: issue.number          ### JSON path in the payload
          value: 17     ### Expected value in the path provided
        - path: action
          value: edited
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ${{ parameters.testhook1.issue.id}} ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
      Write-Host ${{ parameters.testhook1.repository.name}}
