resources:
  webhooks:
    - webhook: testhook1          ### Webhook alias
      connection: FromGitHub    ### Incoming webhook service connection
      filters:
        - path: repository.name      ### JSON path in the payload
          value: 1030new     ### Expected value in the path provided
        - path: action
          value: edited
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ${{ parameters.MyWebhookTrigger.repositoryName}} ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
      Write-Host ${{ parameters.MyWebhookTrigger.component.group}}
